#!/usr/bin/env node
/**
 * LaTeX (moderncv) versions of the CV, generated from data/cv.json so they
 * always carry the same content as the website and its PDFs.
 *
 *   npm run latex          write latex/cv-en.tex and latex/cv-el.tex,
 *                          then compile them with XeLaTeX if it is installed
 *
 * The .tex files are moderncv ("classic" style) and also compile on Overleaf
 * (set the compiler to XeLaTeX). Font: IBM Plex Sans, the website's text
 * face, which has a properly designed Greek — both languages use it.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const HERE = dirname(fileURLToPath(import.meta.url));
const data = JSON.parse(readFileSync(join(HERE, '..', 'data', 'cv.json'), 'utf8'));
const { site, shared } = data;

/* Words the site doesn't need but a paper CV does. */
const LABELS = {
  en: { summary: 'Professional Summary', country: 'Greece', title: 'Curriculum Vitae' },
  el: { summary: 'Επαγγελματικό προφίλ', country: 'Ελλάδα', title: 'Βιογραφικό σημείωμα' }
};

const tex = (s) => String(s)
  .replace(/\\/g, '\\textbackslash{}')
  .replace(/([&%$#_{}])/g, '\\$1')
  .replace(/~/g, '\\textasciitilde{}')
  .replace(/\^/g, '\\textasciicircum{}')
  .replace(/ · /g, ' \\textperiodcentered{} ');
/* Date ranges ("2019 — 2025") take an en dash without spaces: 2019–2025.
 * The character itself, not "--": Greek fonts under polyglossia skip TeX ligatures. */
const dates = (s) => tex(s).replace(/ — /g, '–');
const items = (a) => a && a.length
  ? `\\begin{itemize}\n${a.map((x) => `      \\item ${tex(x)}`).join('\n')}\n    \\end{itemize}` : '';
const lowerFirst = (s) => s.charAt(0).toLocaleLowerCase() + s.slice(1);
const bare = (u) => u.replace(/^https?:\/\/(www\.)?/, '').replace(/\/$/, '');

/* IBM Plex Sans, loaded by file name (XeLaTeX on macOS does not find TeX-tree
 * fonts by family name). SemiBold for bold, as on the website. */
const PLEX = 'IBMPlexSans-Regular.otf}[BoldFont=IBMPlexSans-SemiBold.otf, ItalicFont=IBMPlexSans-Italic.otf, BoldItalicFont=IBMPlexSans-SemiBoldItalic.otf]';

function document(lang) {
  const d = data[lang], L = LABELS[lang];
  const [first, ...rest] = d.meta.name.split(' ');
  const url = `${site.origin}/${lang}/`;

  /* Roles held at the same company: a hairline in the date column joins each
   * date to the next, as on the website. Drawn with TikZ between two marks. */
  let group = 0;
  const jobs = d.jobs.map((j) => {
    if (!j.roles) return `  \\cventry{${dates(j.date)}}{${tex(j.title)}}{${tex(j.org)}}{}{}{\n    ${items(j.pts)}}`;
    const g = group++;
    const roles = j.roles.map((r, i) =>
      `  \\cventry{\\cvmark{g${g}r${i}}${i ? `\\cvlink{g${g}r${i - 1}}{g${g}r${i}}` : ''}${dates(r.date)}}{${tex(r.title)}}{}{}{}{\n    ${items(r.pts)}}`).join('\n');
    return `  \\cvitem{}{\\textbf{${tex(j.co)}} \\textperiodcentered{} ${dates(j.meta)}}\n${roles}`;
  }).join('\n');

  const skills = d.skills.map((s) =>
    `  \\cvitem{${tex(s.h)}}{${tex(s.text)}${s.sub ? ` (${tex(lowerFirst(s.sub))})` : ''}}`).join('\n');

  /* Contact block: icons in their own fixed-width column, text left-aligned
   * beside them, the whole block set flush right. */
  const contact = [
    ['\\faIcon{location-dot}', `${tex(d.ui.place)}, ${tex(L.country)}`],
    ['\\faIcon{mobile-screen}', `\\href{tel:${shared.phoneHref}}{${tex(shared.phoneDisplay)}}`],
    ['\\faIcon[regular]{envelope}', `\\href{mailto:${shared.email}}{${tex(shared.email)}}`],
    ['\\faIcon{earth-europe}', `\\href{${url}}{${tex(bare(site.origin))}}`],
    ['\\faIcon{linkedin-in}', `\\href{${shared.linkedin}}{${tex(bare(shared.linkedin))}}`],
    ['\\faIcon{github}', `\\href{${shared.github}}{${tex(bare(shared.github))}}`]
  ].map(([icon, text]) => `      \\makebox[1.1em][c]{\\color{black!45}${icon}} & ${text}\\\\`).join('\n');

  const langSetup = lang === 'el'
    ? `\\usepackage{polyglossia}
\\setmainlanguage{greek}
\\setotherlanguage{english}
\\newfontfamily\\greekfont{${PLEX}
\\newfontfamily\\greekfontsf{${PLEX}
\\newfontfamily\\greekfonttt{cmuntt.otf}`
    : `\\usepackage{polyglossia}
\\setmainlanguage[variant=british]{english}`;

  return `% Generated by latex/build-latex.mjs from data/cv.json — edit the JSON, not this file.
% Compile with XeLaTeX (on Overleaf: Menu → Compiler → XeLaTeX), twice: the
% line joining roles at the same company is placed on the second run.
\\documentclass[10pt,a4paper,sans]{moderncv}
\\moderncvstyle{classic}
\\moderncvcolor{black}
\\usepackage[scale={0.8,0.87}]{geometry}  % a little less top/bottom margin, so sections fit where they belong
\\usepackage{fontspec}
\\setsansfont{${PLEX}
\\setmainfont{${PLEX}
\\setmonofont{cmuntt.otf}
${langSetup}
\\newfontfamily\\plexlight{IBMPlexSans-Light.otf}
\\usepackage{array}
\\usepackage{qrcode}
\\usepackage{tikz}
\\usepackage{needspace}
% Never leave a section heading alone at the foot of a page.
\\let\\cvsectionplain\\section
\\renewcommand*{\\section}[1]{\\needspace{5\\baselineskip}\\cvsectionplain{#1}}
\\setlength{\\hintscolumnwidth}{3.1cm}
\\renewcommand*{\\firstnamestyle}[1]{{\\fontsize{32}{36}\\plexlight\\textcolor{firstnamecolor}{#1}}}
\\renewcommand*{\\lastnamestyle}[1]{{\\fontsize{32}{36}\\mdseries\\textcolor{lastnamecolor}{#1}}}
\\renewcommand*{\\titlefont}{\\large\\mdseries\\itshape}

% Marks and a hairline joining consecutive roles at one company.
\\newcommand*{\\cvmark}[1]{\\tikz[remember picture,overlay]\\coordinate (#1);}
\\newcommand*{\\cvlink}[2]{\\tikz[remember picture,overlay]\\draw[black!28, line width=0.5pt]
  ([xshift=1.6pt,yshift=-4pt]#1) -- ([xshift=1.6pt,yshift=10pt]#2);}

% Header: name and headline on the left; contact details on the right as a
% two-column table (icon, text), so every line starts at the same place.
\\makeatletter
\\renewcommand*{\\makecvhead}{%
  \\recomputecvlengths%
  \\@initializebox{\\makecvheaddetailsbox}%
  \\savebox{\\makecvheaddetailsbox}{{\\small\\upshape\\renewcommand{\\arraystretch}{1.3}%
    \\begin{tabular}[b]{@{}l@{\\hspace{0.65em}}>{\\color{black!80}}l@{}}
${contact}
    \\end{tabular}}}%
  \\@initializelength{\\makecvheaddetailswidth}%
  \\settowidth{\\makecvheaddetailswidth}{\\usebox{\\makecvheaddetailsbox}}%
  \\setlength{\\makecvheadnamewidth}{\\textwidth-\\makecvheaddetailswidth-1em}%
  \\@initializebox{\\makecvheadnamebox}%
  \\savebox{\\makecvheadnamebox}{%
    \\begin{minipage}[b]{\\makecvheadnamewidth}%
      \\raggedright\\firstnamestyle{\\@firstname\\ }\\lastnamestyle{\\@lastname}%
      \\ifthenelse{\\equal{\\@title}{}}{}{\\\\[1em]\\titlestyle{\\@title}}%
    \\end{minipage}}%
  \\usebox{\\makecvheadnamebox}\\hfill\\usebox{\\makecvheaddetailsbox}%
  \\par\\vspace{2.5em}}
\\makeatother

\\name{${tex(first)}}{${tex(rest.join(' '))}}
\\title{${tex(d.role)}${d.roleAt ? `\\texorpdfstring{\\\\}{ · }${tex(d.roleAt)}` : ''}}  % role, then degree on its own line

\\begin{document}
% moderncv loads hyperref at \\begin{document}, so the PDF metadata is set here.
\\hypersetup{pdftitle={${tex(d.meta.name)} -- ${tex(L.title)}}, pdfauthor={${tex(d.meta.name)}}, pdflang={${lang}}}
\\makecvtitle

\\section{${tex(L.summary)}}
${tex(d.intro)}

\\section{${tex(d.h.exp)}}
${jobs}

\\section{${tex(d.h.skills)}}
${skills}

\\section{${tex(d.h.edu)}}
${d.edu.map((e) => `  \\cventry{${dates(e.date)}}{${tex(e.title)}}{${tex(e.org)}}{}{}{${e.note ? tex(e.note) : ''}}`).join('\n')}

\\section{${tex(d.h.sem)}}
${d.sem.map((s) => `  \\cvitem{${dates(s.date)}}{${tex(s.title)} – ${tex(s.org)}}`).join('\n')}

\\section{${tex(d.h.lang)}}
${d.languages.map((g) => `  \\cvitem{${tex(g.name)}}{${tex(g.lvl)}${g.cert ? ` \\textperiodcentered{} ${tex(g.cert)}` : ''}}`).join('\n')}

% QR code to the matching language page of the website, for printed copies:
% the code sits in the date column, its caption centred beside it.
\\bigskip
\\noindent\\parbox[c]{\\hintscolumnwidth}{\\raggedleft\\qrcode[height=1.9cm]{${url}}}%
\\hspace{\\separatorcolumnwidth}%
\\parbox[c]{\\maincolumnwidth}{\\small\\color{black!70}${tex(d.ui.online)}\\\\[2pt]{\\color{black}\\href{${url}}{${tex(bare(url))}/}}}

\\end{document}
`;
}

for (const lang of site.languages) {
  writeFileSync(join(HERE, `cv-${lang}.tex`), document(lang));
  console.log(`  ✓ latex/cv-${lang}.tex`);
}

/* Compile when a TeX installation is present (MacTeX, TeX Live). */
const xelatex = ['/Library/TeX/texbin/xelatex', '/usr/bin/xelatex', 'xelatex'].find((p) => p === 'xelatex' || existsSync(p));
if (!process.argv.includes('--no-pdf')) {
  for (const lang of site.languages) {
    try {
      for (let pass = 0; pass < 2; pass++) {   // second pass: page count in the footer, TikZ line positions
        execFileSync(xelatex, ['-interaction=nonstopmode', '-halt-on-error', `cv-${lang}.tex`], { cwd: HERE, stdio: 'pipe' });
      }
      console.log(`  ✓ latex/cv-${lang}.pdf`);
    } catch (e) {
      const log = existsSync(join(HERE, `cv-${lang}.log`)) ? readFileSync(join(HERE, `cv-${lang}.log`), 'utf8') : String(e);
      console.error(`  ! cv-${lang}.tex did not compile:\n${log.split('\n').filter((l) => l.startsWith('!')).slice(0, 5).join('\n') || String(e.message).slice(0, 400)}`);
      process.exitCode = 1;
    }
  }
}
