#!/usr/bin/env node
/**
 * LaTeX (moderncv) versions of the CV, generated from data/cv.json so they
 * always carry the same content as the website and its PDFs.
 *
 *   npm run latex          write latex/cv-en.tex and latex/cv-el.tex,
 *                          then compile them with XeLaTeX if it is installed
 *
 * The .tex files are plain moderncv and also compile on Overleaf
 * (set the compiler to XeLaTeX). Fonts: CMU Sans Serif, the Unicode version
 * of the Latin Modern typeface in the original CVs, which includes Greek.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const HERE = dirname(fileURLToPath(import.meta.url));
const data = JSON.parse(readFileSync(join(HERE, '..', 'data', 'cv.json'), 'utf8'));
const { shared } = data;

/* Words the site doesn't need but a paper CV does. */
const LABELS = {
  en: { summary: 'Professional Summary', country: 'Greece', title: 'Curriculum Vitae' },
  el: { summary: 'Επαγγελματικό προφίλ', country: 'Ελλάδα', title: 'Βιογραφικό σημείωμα' }
};

const tex = (s) => String(s)
  .replace(/\\/g, '\\textbackslash{}')
  .replace(/([&%$#_{}])/g, '\\$1')
  .replace(/~/g, '\\textasciitilde{}')
  .replace(/\^/g, '\\textasciicircum{}')
  .replace(/ · /g, ' \\textperiodcentered{} ');
/* Date ranges ("2019 — 2025") take an en dash without spaces: 2019–2025.
 * The character itself, not "--": Greek fonts under polyglossia skip TeX ligatures. */
const dates = (s) => tex(s).replace(/ — /g, '–');
const items = (a) => a && a.length
  ? `\\begin{itemize}\n${a.map((x) => `      \\item ${tex(x)}`).join('\n')}\n    \\end{itemize}` : '';
const lowerFirst = (s) => s.charAt(0).toLocaleLowerCase() + s.slice(1);

function document(lang) {
  const d = data[lang], L = LABELS[lang];
  const [first, ...rest] = d.meta.name.split(' ');

  const jobs = d.jobs.map((j) => j.roles
    ? `  \\cvitem{}{\\textbf{${tex(j.co)}} \\textperiodcentered{} ${dates(j.meta)}}\n` +
      j.roles.map((r) => `  \\cventry{${dates(r.date)}}{${tex(r.title)}}{}{}{}{\n    ${items(r.pts)}}`).join('\n')
    : `  \\cventry{${dates(j.date)}}{${tex(j.title)}}{${tex(j.org)}}{}{}{\n    ${items(j.pts)}}`).join('\n');

  const skills = d.skills.map((s) =>
    `  \\cvitem{${tex(s.h)}}{${tex(s.text)}${s.sub ? ` (${tex(lowerFirst(s.sub))})` : ''}}`).join('\n');

  const langSetup = lang === 'el'
    ? `\\usepackage{polyglossia}
\\setmainlanguage{greek}
\\setotherlanguage{english}
\\newfontfamily\\greekfont{cmunrm.otf}[BoldFont=cmunbx.otf, ItalicFont=cmunti.otf, BoldItalicFont=cmunbi.otf]
\\newfontfamily\\greekfontsf{cmunss.otf}[BoldFont=cmunsx.otf, ItalicFont=cmunsi.otf, BoldItalicFont=cmunso.otf]`
    : `\\usepackage{polyglossia}
\\setmainlanguage[variant=british]{english}`;

  return `% Generated by latex/build-latex.mjs from data/cv.json — edit the JSON, not this file.
% Compile with XeLaTeX (on Overleaf: Menu → Compiler → XeLaTeX).
\\documentclass[11pt,a4paper,sans]{moderncv}
\\moderncvstyle{classic}
\\moderncvcolor{black}
\\usepackage[scale=0.8]{geometry}
\\usepackage{fontspec}
% CMU fonts are loaded by file name: XeLaTeX on macOS does not find TeX-tree fonts by family name.
\\setsansfont{cmunss.otf}[BoldFont=cmunsx.otf, ItalicFont=cmunsi.otf, BoldItalicFont=cmunso.otf]
\\setmainfont{cmunrm.otf}[BoldFont=cmunbx.otf, ItalicFont=cmunti.otf, BoldItalicFont=cmunbi.otf]
${langSetup}
\\setlength{\\hintscolumnwidth}{3.1cm}
${lang === 'el' ? '% The Greek headline is longer: one size down keeps its first line on one line.\n\\renewcommand*{\\titlefont}{\\Large\\mdseries\\slshape}\n' : ''}
\\name{${tex(first)}}{${tex(rest.join(' '))}}
\\title{${tex(d.role)}${d.roleAt ? `\\texorpdfstring{\\\\}{ · }${tex(d.roleAt)}` : ''}}  % role, then degree on its own line
\\address{${tex(d.ui.place)}}{${tex(L.country)}}
\\phone[mobile]{${tex(shared.phoneDisplay)}}
\\email{${tex(shared.email)}}
\\homepage{${tex(data.site.origin.replace(/^https:\/\//, ''))}}
\\social[linkedin]{${tex(shared.linkedin.split('/').filter(Boolean).pop())}}
\\social[github]{${tex(shared.github.split('/').filter(Boolean).pop())}}

\\begin{document}
% moderncv loads hyperref at \\begin{document}, so the PDF metadata is set here.
\\hypersetup{pdftitle={${tex(d.meta.name)} -- ${tex(L.title)}}, pdfauthor={${tex(d.meta.name)}}, pdflang={${lang}}}
\\makecvtitle

\\section{${tex(L.summary)}}
${tex(d.intro)}

\\section{${tex(d.h.exp)}}
${jobs}

\\section{${tex(d.h.skills)}}
${skills}

\\section{${tex(d.h.edu)}}
${d.edu.map((e) => `  \\cventry{${dates(e.date)}}{${tex(e.title)}}{${tex(e.org)}}{}{}{${e.note ? tex(e.note) : ''}}`).join('\n')}

\\section{${tex(d.h.sem)}}
${d.sem.map((s) => `  \\cvitem{${dates(s.date)}}{${tex(s.title)} – ${tex(s.org)}}`).join('\n')}

\\section{${tex(d.h.lang)}}
${d.languages.map((g) => `  \\cvitem{${tex(g.name)}}{${tex(g.lvl)}${g.cert ? ` \\textperiodcentered{} ${tex(g.cert)}` : ''}}`).join('\n')}

\\end{document}
`;
}

for (const lang of data.site.languages) {
  writeFileSync(join(HERE, `cv-${lang}.tex`), document(lang));
  console.log(`  ✓ latex/cv-${lang}.tex`);
}

/* Compile when a TeX installation is present (MacTeX, TeX Live). */
const xelatex = ['/Library/TeX/texbin/xelatex', '/usr/bin/xelatex', 'xelatex'].find((p) => p === 'xelatex' || existsSync(p));
if (!process.argv.includes('--no-pdf')) {
  for (const lang of data.site.languages) {
    try {
      for (let pass = 0; pass < 2; pass++) {   // second pass settles the page count in the footer
        execFileSync(xelatex, ['-interaction=nonstopmode', '-halt-on-error', `cv-${lang}.tex`], { cwd: HERE, stdio: 'pipe' });
      }
      console.log(`  ✓ latex/cv-${lang}.pdf`);
    } catch (e) {
      const log = existsSync(join(HERE, `cv-${lang}.log`)) ? readFileSync(join(HERE, `cv-${lang}.log`), 'utf8') : String(e);
      console.error(`  ! cv-${lang}.tex did not compile:\n${log.split('\n').filter((l) => l.startsWith('!')).slice(0, 5).join('\n') || String(e.message).slice(0, 400)}`);
      process.exitCode = 1;
    }
  }
}
